# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import remote_writer_pb2 as perfetto_dot_remote__writer_dot_remote__writer__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in perfetto/remote_writer/remote_writer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TraceDataServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendTraceData = channel.unary_unary(
                '/perfetto.protos.TraceDataService/SendTraceData',
                request_serializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataRequest.SerializeToString,
                response_deserializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataResponse.FromString,
                _registered_method=True)
        self.SendTraceDataStream = channel.stream_unary(
                '/perfetto.protos.TraceDataService/SendTraceDataStream',
                request_serializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataRequest.SerializeToString,
                response_deserializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataResponse.FromString,
                _registered_method=True)


class TraceDataServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendTraceData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTraceDataStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TraceDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendTraceData': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTraceData,
                    request_deserializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataRequest.FromString,
                    response_serializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataResponse.SerializeToString,
            ),
            'SendTraceDataStream': grpc.stream_unary_rpc_method_handler(
                    servicer.SendTraceDataStream,
                    request_deserializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataRequest.FromString,
                    response_serializer=perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'perfetto.protos.TraceDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('perfetto.protos.TraceDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TraceDataService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendTraceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/perfetto.protos.TraceDataService/SendTraceData',
            perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataRequest.SerializeToString,
            perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendTraceDataStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/perfetto.protos.TraceDataService/SendTraceDataStream',
            perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataRequest.SerializeToString,
            perfetto_dot_remote__writer_dot_remote__writer__pb2.TraceDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
