# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: perfetto/remote_writer/remote_writer.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'perfetto/remote_writer/remote_writer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*perfetto/remote_writer/remote_writer.proto\x12\x0fperfetto.protos\".\n\x10TraceDataRequest\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x0c\n\x04size\x18\x02 \x01(\x05\"#\n\x11TraceDataResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xcc\x01\n\x10TraceDataService\x12V\n\rSendTraceData\x12!.perfetto.protos.TraceDataRequest\x1a\".perfetto.protos.TraceDataResponse\x12`\n\x13SendTraceDataStream\x12!.perfetto.protos.TraceDataRequest\x1a\".perfetto.protos.TraceDataResponse\"\x00(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'perfetto.remote_writer.remote_writer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACEDATAREQUEST']._serialized_start=63
  _globals['_TRACEDATAREQUEST']._serialized_end=109
  _globals['_TRACEDATARESPONSE']._serialized_start=111
  _globals['_TRACEDATARESPONSE']._serialized_end=146
  _globals['_TRACEDATASERVICE']._serialized_start=149
  _globals['_TRACEDATASERVICE']._serialized_end=353
# @@protoc_insertion_point(module_scope)
