
syntax = "proto2";

package perfetto.protos;

// next id: 417
enum ArmGpuCounters {
    MALI_GPU_UNSPECIFIED = 0;
    MALI_GPU_ACTIVE_CY = 1;
    MALI_GPUIRQ_ACTIVE_CY = 2;
    MALI_FRAG_QUEUE_JOB = 3;
    MALI_FRAG_QUEUE_TASK = 4;
    MALI_FRAG_QUEUE_ACTIVE_CY = 5;
    MALI_NON_FRAG_QUEUE_JOB = 6;
    MALI_NON_FRAG_QUEUE_TASK = 7;
    MALI_NON_FRAG_QUEUE_ACTIVE_CY = 8;
    MALI_RES_QUEUE_JOB = 9;
    MALI_RES_QUEUE_TASK = 10;
    MALI_RES_QUEUE_ACTIVE_CY = 11;
    MALI_EXT_BUS_WR_BT = 12;
    MALI_EXT_BUS_RD_BT = 13;
    MALI_EXT_BUS_RD_STALL_CY = 14;
    MALI_EXT_BUS_WR_STALL_CY = 15;
    MALI_FRAG_ACTIVE_CY = 16;
    MALI_FRAG_RD_PRIM = 17;
    MALI_FRAG_THREAD = 18;
    MALI_FRAG_HELP_THREAD = 19;
    MALI_FRAG_RAST_QD = 20;
    MALI_FRAG_EZS_TEST_QD = 21;
    MALI_FRAG_EZS_KILL_QD = 22;
    MALI_FRAG_LZS_TEST_TD = 23;
    MALI_FRAG_LZS_KILL_TD = 24;
    MALI_FRAG_TILE = 25;
    MALI_FRAG_TILE_KILL = 26;
    MALI_NON_FRAG_ACTIVE_CY = 27;
    MALI_NON_FRAG_THREAD = 28;
    MALI_CORE_ACTIVE_CY = 29;
    MALI_ENG_INSTR = 30;
    MALI_LS_ISSUE_CY = 31;
    MALI_TEX_INSTR = 32;
    MALI_TEX_FILT_ISSUE_CY = 33;
    MALI_LS_RD_HIT_CY = 34;
    MALI_LS_WR_HIT_CY = 35;
    MALI_GEOM_TRIANGLE_PRIM = 36;
    MALI_GEOM_POINT_PRIM = 37;
    MALI_GEOM_LINE_PRIM = 38;
    MALI_GEOM_FRONT_FACE_PRIM = 39;
    MALI_GEOM_BACK_FACE_PRIM = 40;
    MALI_GEOM_VISIBLE_PRIM = 41;
    MALI_GEOM_FACE_XY_PLANE_CULL_PRIM = 42;
    MALI_GEOM_Z_PLANE_CULL_PRIM = 43;
    MALI_TILER_ACTIVE_CY = 44;
    MALI_GPUIRQ_UTIL = 45;
    MALI_FRAG_QUEUE_UTIL = 46;
    MALI_NON_FRAG_QUEUE_UTIL = 47;
    MALI_EXT_BUS_RD_BY = 48;
    MALI_EXT_BUS_WR_BY = 49;
    MALI_EXT_BUS_RD_STALL_RATE = 50;
    MALI_EXT_BUS_WR_STALL_RATE = 51;
    MALI_TILER_UTIL = 52;
    MALI_GEOM_TOTAL_PRIM = 53;
    MALI_GEOM_VISIBLE_RATE = 54;
    MALI_GEOM_TOTAL_CULL_PRIM = 55;
    MALI_GEOM_FACE_XY_PLANE_CULL_RATE = 56;
    MALI_GEOM_Z_PLANE_CULL_RATE = 57;
    MALI_NON_FRAG_UTIL = 58;
    MALI_NON_FRAG_THROUGHPUT_CY = 59;
    MALI_FRAG_UTIL = 60;
    MALI_FRAG_THROUGHPUT_CY = 61;
    MALI_FRAG_HELP_TD_RATE = 62;
    MALI_FRAG_EZS_TEST_RATE = 63;
    MALI_FRAG_EZS_KILL_RATE = 64;
    MALI_FRAG_LZS_TEST_RATE = 65;
    MALI_FRAG_LZS_KILL_RATE = 66;
    MALI_FRAG_OVERDRAW = 67;
    MALI_FRAG_TILE_KILL_RATE = 68;
    MALI_CORE_UTIL = 69;
    MALI_ALU_UTIL = 70;
    MALI_TEX_SAMPLE = 71;
    MALI_TEX_CPI = 72;
    MALI_TEX_UTIL = 73;
    MALI_TEX_ISSUE_CY = 74;
    MALI_LS_UTIL = 75;
    MALI_GPU_PIX = 76;
    MALI_GPU_CY_PER_PIX = 77;
    MALI_FRAG_QUEUE_WAIT_RD_CY = 78;
    MALI_FRAG_QUEUE_WAIT_ISSUE_CY = 79;
    MALI_FRAG_QUEUE_WAIT_DEP_CY = 80;
    MALI_FRAG_QUEUE_WAIT_FINISH_CY = 81;
    MALI_NON_FRAG_QUEUE_WAIT_RD_CY = 82;
    MALI_NON_FRAG_QUEUE_WAIT_ISSUE_CY = 83;
    MALI_NON_FRAG_QUEUE_WAIT_DEP_CY = 84;
    MALI_NON_FRAG_QUEUE_WAIT_FINISH_CY = 85;
    MALI_RES_QUEUE_WAIT_RD_CY = 86;
    MALI_RES_QUEUE_WAIT_ISSUE_CY = 87;
    MALI_RES_QUEUE_WAIT_DEP_CY = 88;
    MALI_RES_QUEUE_WAIT_FINISH_CY = 89;
    MALI_MMUL2_HIT = 90;
    MALI_MMUL2_RD = 91;
    MALI_MMU_LOOKUP = 92;
    MALI_L2_CACHE_LOOKUP = 93;
    MALI_L2_CACHE_RD_LOOKUP = 94;
    MALI_L2_CACHE_WR_LOOKUP = 95;
    MALI_FRAG_FPK_ACTIVE_CY = 96;
    MALI_LS_RD_CY = 97;
    MALI_LS_WR_CY = 98;
    MALI_LS_ATOMIC = 99;
    MALI_TILER_POS_CACHE_HIT = 100;
    MALI_TILER_POS_CACHE_MISS = 101;
    MALI_FRAG_FPKB_UTIL = 102;
    MALI_FRAG_QUEUE_WAIT_FLUSH_CY = 103;
    MALI_NON_FRAG_QUEUE_WAIT_FLUSH_CY = 104;
    MALI_RES_QUEUE_WAIT_FLUSH_CY = 105;
    MALI_L2_CACHE_FLUSH = 106;
    MALI_GEOM_SAMPLE_CULL_PRIM = 107;
    MALI_TILER_RD_BT = 108;
    MALI_TILER_WR_BT = 109;
    MALI_GEOM_POS_SHAD_TASK = 110;
    MALI_TILER_POS_SHAD_STALL_CY = 111;
    MALI_TILER_POS_SHAD_FIFO_FULL_CY = 112;
    MALI_TILER_VAR_CACHE_HIT = 113;
    MALI_TILER_VAR_CACHE_MISS = 114;
    MALI_GEOM_VAR_SHAD_TASK = 115;
    MALI_TILER_VAR_SHAD_STALL_CY = 116;
    MALI_FRAG_RAST_PRIM = 117;
    MALI_FRAG_WARP = 118;
    MALI_FRAG_PART_WARP = 119;
    MALI_FRAG_EZS_UPDATE_QD = 120;
    MALI_FRAG_LZS_TEST_QD = 121;
    MALI_FRAG_LZS_KILL_QD = 122;
    MALI_FRAG_OPAQUE_QD = 123;
    MALI_NON_FRAG_TASK = 124;
    MALI_NON_FRAG_WARP = 125;
    MALI_ENG_ACTIVE_CY = 126;
    MALI_ENG_DIVERGED_INSTR = 127;
    MALI_ENG_STARVE_CY = 128;
    MALI_TEX_QUADS = 129;
    MALI_TEX_QUAD_PASS = 130;
    MALI_TEX_QUAD_PASS_DESC_MISS = 131;
    MALI_TEX_QUAD_PASS_MIP = 132;
    MALI_TEX_QUAD_PASS_TRI = 133;
    MALI_TEX_CACHE_FETCH = 134;
    MALI_TEX_CACHE_COMPRESS_FETCH = 135;
    MALI_TEX_CACHE_LOOKUP = 136;
    MALI_LS_FULL_RD = 137;
    MALI_LS_PART_RD = 138;
    MALI_LS_FULL_WR = 139;
    MALI_LS_PART_WR = 140;
    MALI_VAR_INSTR = 141;
    MALI_VAR32_ISSUE_SLOT = 142;
    MALI_VAR16_ISSUE_SLOT = 143;
    MALI_ATTR_INSTR = 144;
    MALI_SC_BUS_FFEL2_RD_BT = 145;
    MALI_SC_BUS_FFE_EXT_RD_BT = 146;
    MALI_SC_BUS_LSL2_RD_BT = 147;
    MALI_SC_BUS_LS_EXT_RD_BT = 148;
    MALI_SC_BUS_TEX_L2_RD_BT = 149;
    MALI_SC_BUS_TEX_EXT_RD_BT = 150;
    MALI_SC_BUS_OTHER_L2_RD_BT = 151;
    MALI_SC_BUS_LSWB_WR_BT = 152;
    MALI_SC_BUS_TILE_WR_BT = 153;
    MALI_SC_BUS_LS_OTHER_WR_BT = 154;
    MALI_MMUL3_RD = 155;
    MALI_MMUL3_HIT = 156;
    MALI_MMUS2_LOOKUP = 157;
    MALI_MMUS2L3_RD = 158;
    MALI_MMUS2L2_RD = 159;
    MALI_MMUS2L3_HIT = 160;
    MALI_MMUS2L2_HIT = 161;
    MALI_L2_CACHE_RD = 162;
    MALI_L2_CACHE_RD_STALL_CY = 163;
    MALI_L2_CACHE_WR = 164;
    MALI_L2_CACHE_WR_STALL_CY = 165;
    MALI_L2_CACHE_SNP = 166;
    MALI_L2_CACHE_SNP_STALL_CY = 167;
    MALI_L2_CACHE_L1_RD = 168;
    MALI_L2_CACHE_L1_RD_STALL_CY = 169;
    MALI_L2_CACHE_L1_WR = 170;
    MALI_L2_CACHE_SNP_LOOKUP = 171;
    MALI_EXT_BUS_RD = 172;
    MALI_EXT_BUS_RD_NO_SNOOP = 173;
    MALI_EXT_BUS_RD_UNIQUE = 174;
    MALI_EXT_BUS_RD_OTQ1 = 175;
    MALI_EXT_BUS_RD_OTQ2 = 176;
    MALI_EXT_BUS_RD_OTQ3 = 177;
    MALI_EXT_BUS_RD_LAT0 = 178;
    MALI_EXT_BUS_RD_LAT128 = 179;
    MALI_EXT_BUS_RD_LAT192 = 180;
    MALI_EXT_BUS_RD_LAT256 = 181;
    MALI_EXT_BUS_RD_LAT320 = 182;
    MALI_EXT_BUS_WR = 183;
    MALI_EXT_BUS_WR_NO_SNOOP_FULL = 184;
    MALI_EXT_BUS_WR_NO_SNOOP_PART = 185;
    MALI_EXT_BUS_WR_SNOOP_FULL = 186;
    MALI_EXT_BUS_WR_SNOOP_PART = 187;
    MALI_EXT_BUS_WR_OTQ1 = 188;
    MALI_EXT_BUS_WR_OTQ2 = 189;
    MALI_EXT_BUS_WR_OTQ3 = 190;
    MALI_L2_CACHE_INC_SNP = 191;
    MALI_L2_CACHE_INC_SNP_STALL_CY = 192;
    MALI_L2_CACHE_RD_MISS_RATE = 193;
    MALI_L2_CACHE_WR_MISS_RATE = 194;
    MALI_EXT_BUS_RD_LAT384 = 195;
    MALI_EXT_BUS_RD_OTQ4 = 196;
    MALI_EXT_BUS_WR_OTQ4 = 197;
    MALI_GEOM_SAMPLE_CULL_RATE = 198;
    MALI_GEOM_POS_SHAD_THREAD = 199;
    MALI_GEOM_POS_SHAD_THREAD_PER_PRIM = 200;
    MALI_TILER_POS_CACHE_HIT_RATE = 201;
    MALI_GEOM_VAR_SHAD_THREAD = 202;
    MALI_GEOM_VAR_SHAD_THREAD_PER_PRIM = 203;
    MALI_TILER_VAR_CACHE_HIT_RATE = 204;
    MALI_FRAG_OPAQUE_QD_RATE = 205;
    MALI_FRAG_TRANSPARENT_QD = 206;
    MALI_FRAG_SHADED_QD = 207;
    MALI_FRAG_PART_WARP_RATE = 208;
    MALI_FRAG_EZS_UPDATE_RATE = 209;
    MALI_FRAG_FPK_KILL_QD = 210;
    MALI_FRAG_FPK_KILL_RATE = 211;
    MALI_ENG_DIVERGED_INSTR_RATE = 212;
    MALI_TEX_CACHE_UTIL = 213;
    MALI_TEX_MIP_INSTR_RATE = 214;
    MALI_TEX_CACHE_COMPRESS_FETCH_RATE = 215;
    MALI_TEX_TRI_INSTR_RATE = 216;
    MALI_VAR32_ISSUE_CY = 217;
    MALI_VAR16_ISSUE_CY = 218;
    MALI_VAR_ISSUE_CY = 219;
    MALI_VAR_UTIL = 220;
    MALI_SC_BUS_FFEL2_RD_BY = 221;
    MALI_SC_BUS_FFE_EXT_RD_BY = 222;
    MALI_SC_BUS_LSL2_RD_BY = 223;
    MALI_SC_BUS_LSL2_RD_BY_PER_RD = 224;
    MALI_SC_BUS_LS_EXT_RD_BY = 225;
    MALI_SC_BUS_LS_EXT_RD_BY_PER_RD = 226;
    MALI_SC_BUS_TEX_L2_RD_BY = 227;
    MALI_SC_BUS_TEX_L2_RD_BY_PER_RD = 228;
    MALI_SC_BUS_TEX_EXT_RD_BY = 229;
    MALI_SC_BUS_TEX_EXT_RD_BY_PER_RD = 230;
    MALI_SC_BUS_LS_WR_BT = 231;
    MALI_SC_BUS_LS_WR_BY = 232;
    MALI_SC_BUS_LS_WR_BY_PER_WR = 233;
    MALI_SC_BUS_TILE_WR_BY = 234;
    MALI_CORE_ALL_REGS_WARP = 235;
    MALI_CORE_FULL_WARP = 236;
    MALI_CORE_ALL_REGS_WARP_RATE = 237;
    MALI_CORE_FULL_WARP_RATE = 238;
    MALI_TEX_MIP_INSTR = 239;
    MALI_TEX_COMPRESS_INSTR = 240;
    MALI_TEX3D_INSTR = 241;
    MALI_TEX_TRI_INSTR = 242;
    MALI_TEX_COORD_STALL_CY = 243;
    MALI_TEX_DATA_STALL_CY = 244;
    MALI_TEX_PART_DATA_STALL_CY = 245;
    MALI_SC_BUS_OTHER_WR_BT = 246;
    MALI_TEX_COMPRESS_INSTR_RATE = 247;
    MALI_TEX3D_INSTR_RATE = 248;
    MALI_SC_BUS_OTHER_WR_BY = 249;
    MALI_FRAG_RAST_PART_QD = 250;
    MALI_ENG_FMA_INSTR = 251;
    MALI_ENG_CVT_INSTR = 252;
    MALI_ENG_SFU_INSTR = 253;
    MALI_ENG_I_CACHE_MISS = 254;
    MALI_ENG_SW_BLEND_INSTR = 255;
    MALI_TEX_IN_BT = 256;
    MALI_TEX_DESC_STALL_CY = 257;
    MALI_TEX_DATA_FETCH_STALL_CY = 258;
    MALI_TEX_FILT_STALL_CY = 259;
    MALI_TEX_FULL_BI_FILT_CY = 260;
    MALI_TEX_FULL_TRI_FILT_CY = 261;
    MALI_TEX_OUT_MSG = 262;
    MALI_TEX_OUT_BT = 263;
    MALI_FRAG_RAST_PART_QD_RATE = 264;
    MALI_ENG_FMA_PIPE_UTIL = 265;
    MALI_ENG_CVT_PIPE_UTIL = 266;
    MALI_ENG_SFU_PIPE_UTIL = 267;
    MALI_ENG_ARITH_INSTR = 268;
    MALI_ENG_SW_BLEND_RATE = 269;
    MALI_TEX_IN_BUS_UTIL = 270;
    MALI_TEX_OUT_BUS_UTIL = 271;
    MALI_TEX_FILT_FULL_RATE = 272;
    MALI_ANY_ACTIVE_CY = 273;
    MALI_ANY_UTIL = 274;
    MALI_CSFMCU_ACTIVE_CY = 275;
    MALI_GPU_QUEUE_ACTIVE_CY = 276;
    MALI_GPUIRQ = 277;
    MALI_L2_CACHE_FLUSH_CY = 278;
    MALI_VERT_QUEUED_CY = 279;
    MALI_VERT_QUEUE_JOB = 280;
    MALI_VERT_QUEUE_TASK = 281;
    MALI_VERT_QUEUE_TOTAL_ACTIVE_CY = 282;
    MALI_VERT_QUEUE_IRQ_ACTIVE_CY = 283;
    MALI_VERT_QUEUE_ASSIGN_STALL_CY = 284;
    MALI_TILER_QUEUE_DRAIN_STALL_CY = 285;
    MALI_COMP_QUEUED_CY = 286;
    MALI_COMP_QUEUE_JOB = 287;
    MALI_COMP_QUEUE_TASK = 288;
    MALI_COMP_QUEUE_TOTAL_ACTIVE_CY = 289;
    MALI_COMP_QUEUE_IRQ_ACTIVE_CY = 290;
    MALI_COMP_QUEUE_ASSIGN_STALL_CY = 291;
    MALI_COMP_QUEUE_DRAIN_STALL_CY = 292;
    MALI_FRAG_QUEUED_CY = 293;
    MALI_FRAG_QUEUE_TOTAL_ACTIVE_CY = 294;
    MALI_FRAG_QUEUE_IRQ_ACTIVE_CY = 295;
    MALI_FRAG_QUEUE_ASSIGN_STALL_CY = 296;
    MALI_CSFCEU_ACTIVE_CY = 297;
    MALI_CSFLSU_ACTIVE_CY = 298;
    MALI_CSFCS0_ACTIVE_CY = 299;
    MALI_CS0_WAIT_STALL_CY = 300;
    MALI_CSFCS1_ACTIVE_CY = 301;
    MALI_CS1_WAIT_STALL_CY = 302;
    MALI_CSFCS2_ACTIVE_CY = 303;
    MALI_CS2_WAIT_STALL_CY = 304;
    MALI_CSFCS3_ACTIVE_CY = 305;
    MALI_CS3_WAIT_STALL_CY = 306;
    MALI_L2_CACHE_EVICT = 307;
    MALI_L2_CACHE_CLEAN_UNIQUE = 308;
    MALI_VERT_QUEUE_ACTIVE_CY = 309;
    MALI_VERT_QUEUE_UTIL = 310;
    MALI_COMP_QUEUE_ACTIVE_CY = 311;
    MALI_COMP_QUEUE_UTIL = 312;
    MALI_CSFMCU_UTIL = 313;
    MALI_CSFLSU_UTIL = 314;
    MALI_CSFCEU_UTIL = 315;
    MALI_GPU_ACTIVE2_CY = 316;
    MALI_ENG_NARROW_INSTR = 317;
    MALI_FRAG_RAST_COARSE_QD = 318;
    MALI_RTU_TRI = 319;
    MALI_RTU_BOX = 320;
    MALI_RTU_TRI_BIN1 = 321;
    MALI_RTU_TRI_BIN5 = 322;
    MALI_RTU_TRI_BIN9 = 323;
    MALI_RTU_TRI_BIN13 = 324;
    MALI_RTU_BOX_BIN1 = 325;
    MALI_RTU_BOX_BIN5 = 326;
    MALI_RTU_BOX_BIN9 = 327;
    MALI_RTU_BOX_BIN13 = 328;
    MALI_RTU_OPAQUE_HIT = 329;
    MALI_RTU_NON_OPAQUE_HIT = 330;
    MALI_RTU_FIRST_HIT_TERM = 331;
    MALI_RTU_MISS = 332;
    MALI_RTU_RAY = 333;
    MALI_RTU_BOX_ISSUE_CY = 334;
    MALI_RTU_TRI_ISSUE_CY = 335;
    MALI_GEOM_FACE_CULL_PRIM = 336;
    MALI_GEOM_PLANE_CULL_PRIM = 337;
    MALI_GEOM_FACE_CULL_RATE = 338;
    MALI_GEOM_PLANE_CULL_RATE = 339;
    MALI_FRAG_SHAD_RATE = 340;
    MALI_CORE_FRAG_WARP_OCC = 341;
    MALI_ENG_NARROW_INSTR_RATE = 342;
    MALI_RTU_UTIL = 343;
    MALI_BINNING_QUEUED_CY = 344;
    MALI_BINNING_QUEUE_JOB = 345;
    MALI_BINNING_QUEUE_TASK = 346;
    MALI_BINNING_QUEUE_IRQ_ACTIVE_CY = 347;
    MALI_BINNING_QUEUE_ASSIGN_STALL_CY = 348;
    MALI_MAIN_QUEUED_CY = 349;
    MALI_MAIN_QUEUE_JOB = 350;
    MALI_MAIN_QUEUE_TASK = 351;
    MALI_MAIN_QUEUE_IRQ_ACTIVE_CY = 352;
    MALI_MAIN_QUEUE_ASSIGN_STALL_CY = 353;
    MALI_MAIN_ACTIVE_CY = 354;
    MALI_COMP_OR_BINNING_ACTIVE_CY = 355;
    MALI_TEX_L1_CACHE_LOAD_CY = 356;
    MALI_TEX_CACHE_SIMPLE_LOAD_CY = 357;
    MALI_TEX_L1_CACHE_OUTPUT_CY = 358;
    MALI_TEX_L1_CACHE_LOOKUP_CY = 359;
    MALI_TEX_OUT_SINGLE_MSG = 360;
    MALI_TEX_CACHE_LOOKUP_CY = 361;
    MALI_TEX_CACHE_COMPLEX_LOAD_CY = 362;
    MALI_TEX_INDEX_CY = 363;
    MALI_TEX_CLK_STARVED_CY = 364;
    MALI_TEX_CLK_ACTIVE_CY = 365;
    MALI_GEOM_SCISSOR_CULL_PRIM = 366;
    MALI_GEOM_VISIBLE_DVS_PRIM = 367;
    MALI_MAIN_QUEUE_ACTIVE_CY = 368;
    MALI_MAIN_QUEUE_UTIL = 369;
    MALI_BINNING_QUEUE_ACTIVE_CY = 370;
    MALI_BINNING_QUEUE_UTIL = 371;
    MALI_GEOM_SCISSOR_CULL_RATE = 372;
    MALI_COMP_OR_BINNING_UTIL = 373;
    MALI_MAIN_UTIL = 374;
    MALI_CS_DOORBELL_IRQ_CY = 375;
    MALI_MAIN_QUEUE_TOTAL_ACTIVE_CY = 376;
    MALI_BINNING_QUEUE_TOTAL_ACTIVE_CY = 377;
    MALI_CSFCS4_ACTIVE_CY = 378;
    MALI_CS4_WAIT_STALL_CY = 379;
    MALI_CSFCS5_ACTIVE_CY = 380;
    MALI_CS5_WAIT_STALL_CY = 381;
    MALI_FRAG_PRIM = 382;
    MALI_FRAG_PREPASS_CULL_PRIM = 383;
    MALI_FRAG_PREPASS_PRIM = 384;
    MALI_FRAG_PREPASS_UNCULL_PRIM = 385;
    MALI_FRAG_PREPASS_EZS_UPDATE_QD = 386;
    MALI_FRAG_PREPASS_TEST_QD = 387;
    MALI_FRAG_PREPASS_KILL_QD = 388;
    MALI_FRAG_PREPASS_WARP = 389;
    MALI_FRAG_MAIN_PASS_STALL_CY = 390;
    MALI_DEF_VERT_WARP = 391;
    MALI_ENG_TEX_BACKPRESSURE_CY = 392;
    MALI_ENG_VAR_BACKPRESSURE_CY = 393;
    MALI_ENG_BLEND_BACKPRESSURE_CY = 394;
    MALI_ENG_ZS_BACKPRESSURE_CY = 395;
    MALI_ENG_LS_BACKPRESSURE_CY = 396;
    MALI_ENG_ATTR_BACKPRESSURE_CY = 397;
    MALI_ENG_SLOT1_ISSUE_CY = 398;
    MALI_ENG_SLOT_ANY_ISSUE_CY = 399;
    MALI_GEOM_POS_SHAD_PART_TASK = 400;
    MALI_GEOM_VAR_SHAD_PART_TASK = 401;
    MALI_FRAG_PREPASS_KILL_RATE = 402;
    MALI_FRAG_MAIN_PASS_STALL_RATE = 403;
    MALI_FRAG_INPUT_PRIM = 404;
    MALI_FRAG_PREPASS_PRIM_RATE = 405;
    MALI_FRAG_PREPASS_CULL_PRIM_RATE = 406;
    MALI_FRAG_PREPASS_UNCULL_PRIM_RATE = 407;
    MALI_FRAG_PREPASS_WARP_RATE = 408;
    MALI_FRAG_PREPASS_THREAD = 409;
    MALI_FRAG_MAIN_THREAD = 410;
    MALI_ENG_SLOT0_ISSUE_CY = 411;
    MALI_ENG_ATTR_BACKPRESSURE_RATE = 412;
    MALI_ENG_BLEND_BACKPRESSURE_RATE = 413;
    MALI_ENG_LS_BACKPRESSURE_RATE = 414;
    MALI_ENG_TEX_BACKPRESSURE_RATE = 415;
    MALI_ENG_VAR_BACKPRESSURE_RATE = 416;
    MALI_ENG_ZS_BACKPRESSURE_RATE = 417;
}