
import("../../gn/perfetto.gni")
import("../../gn/test.gni")


assert(enable_perfetto_traced_gpu)


executable("traced_gpu") {
  deps = [
    ":traced_gpu_main",
    "../../../gn:default_deps",
  ]
  sources = [ "main.cc" ]
}

source_set("traced_gpu_main") {
  deps = [
    ":proc_descriptors",
    ":producer",
    "../../../gn:default_deps",
    "../../../src/base",
    "../../../src/tracing/ipc/producer",
  ]
  sources = [
    "traced_gpu.cc",
    "traced_gpu.h",
  ]
}


source_set("producer") {
  public_deps = [
    ":common_types",
    ":regs_parsing",
    ":unwinding",
    "../../../include/perfetto/tracing/core",
    "../../../src/tracing/service",  # for metatrace
  ]

  deps = [
    ":proc_descriptors",
    "../../../gn:default_deps",
    "../../../protos/perfetto/common:cpp",
    "../../../protos/perfetto/common:zero",
    "../../../protos/perfetto/config:cpp",
    "../../../protos/perfetto/config/profiling:cpp",
    "../../../protos/perfetto/trace:zero",
    "../../../protos/perfetto/trace/profiling:zero",
    "../../../src/base",
    "../../../src/base:unix_socket",
    "../../../src/traced/probes/ftrace:ftrace_procfs",
    "../../../src/tracing/ipc/producer",
    "../common:callstack_trie",
    "../common:interner",
    "../common:interning_output",
    "../common:proc_cmdline",
    "../common:producer_support",
    "../common:profiler_guardrails",
  ]
  sources = [
    "gpu_producer.cc",
    "gpu_producer.h",
  ]
}


source_set("proc_descriptors") {
  deps = [
    "../../../gn:default_deps",
    "../../../src/base",
  ]
  sources = [
    "proc_descriptors.cc",
    "proc_descriptors.h",
  ]
}