import("../../../../gn/test.gni")

source_set("network_stats") {
  public_deps = [
    "../../../tracing/core",
  ]
  deps = [
    "..:data_source",
    "../../../../gn:default_deps",
    "../../../../include/perfetto/ext/traced",
    "../../../../protos/perfetto/common:zero",
    "../../../../protos/perfetto/trace:zero",
    "../../../base",
  ]
  sources = [
    "network_stats_data_source.cc",
    "network_stats_data_source.h",
  ]
}
