
#ifndef SRC_PROFILING_MTK_DIMPROFD_ARM_GPU_COUNTER_ARM_GPU_COUNTERS_H_
#define SRC_PROFILING_MTK_DIMPROFD_ARM_GPU_COUNTER_ARM_GPU_COUNTERS_H_

#include "perfetto/ext/base/utils.h"
#include "protos/perfetto/common/arm_gpu_counters.pbzero.h"

#include <hwcpipe/hwcpipe_counter.h>
#include <vector>
#include <optional>

namespace perfetto {

namespace profiling {

struct KeyAndCounter {
  const char* str;
  int id;
  // hwcpipe_counter type;
  std::optional<hwcpipe_counter> type;
};

constexpr KeyAndCounter kArmGpuInfoPBKeys[] = {
    {"MaliGPUUnspecified", protos::pbzero::ArmGpuCounters::MALI_GPU_UNSPECIFIED,
     std::nullopt},
    {"MaliGPUActiveCy", protos::pbzero::ArmGpuCounters::MALI_GPU_ACTIVE_CY,
     MaliGPUActiveCy},
    {"MaliGPUIRQActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_GPUIRQ_ACTIVE_CY, MaliGPUIRQActiveCy},
    {"MaliFragQueueJob", protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_JOB,
     MaliFragQueueJob},
    {"MaliFragQueueTask", protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_TASK,
     MaliFragQueueTask},
    {"MaliFragQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_ACTIVE_CY,
     MaliFragQueueActiveCy},
    {"MaliNonFragQueueJob",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_JOB,
     MaliNonFragQueueJob},
    {"MaliNonFragQueueTask",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_TASK,
     MaliNonFragQueueTask},
    {"MaliNonFragQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_ACTIVE_CY,
     MaliNonFragQueueActiveCy},
    {"MaliResQueueJob", protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_JOB,
     MaliResQueueJob},
    {"MaliResQueueTask", protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_TASK,
     MaliResQueueTask},
    {"MaliResQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_ACTIVE_CY,
     MaliResQueueActiveCy},
    {"MaliExtBusWrBt", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_BT,
     MaliExtBusWrBt},
    {"MaliExtBusRdBt", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_BT,
     MaliExtBusRdBt},
    {"MaliExtBusRdStallCy",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_STALL_CY,
     MaliExtBusRdStallCy},
    {"MaliExtBusWrStallCy",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_STALL_CY,
     MaliExtBusWrStallCy},
    {"MaliFragActiveCy", protos::pbzero::ArmGpuCounters::MALI_FRAG_ACTIVE_CY,
     MaliFragActiveCy},
    {"MaliFragRdPrim", protos::pbzero::ArmGpuCounters::MALI_FRAG_RD_PRIM,
     MaliFragRdPrim},
    {"MaliFragThread", protos::pbzero::ArmGpuCounters::MALI_FRAG_THREAD,
     MaliFragThread},
    {"MaliFragHelpThread",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_HELP_THREAD, MaliFragHelpThread},
    {"MaliFragRastQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_RAST_QD,
     MaliFragRastQd},
    {"MaliFragEZSTestQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_EZS_TEST_QD,
     MaliFragEZSTestQd},
    {"MaliFragEZSKillQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_EZS_KILL_QD,
     MaliFragEZSKillQd},
    {"MaliFragLZSTestTd", protos::pbzero::ArmGpuCounters::MALI_FRAG_LZS_TEST_TD,
     MaliFragLZSTestTd},
    {"MaliFragLZSKillTd", protos::pbzero::ArmGpuCounters::MALI_FRAG_LZS_KILL_TD,
     MaliFragLZSKillTd},
    {"MaliFragTile", protos::pbzero::ArmGpuCounters::MALI_FRAG_TILE,
     MaliFragTile},
    {"MaliFragTileKill", protos::pbzero::ArmGpuCounters::MALI_FRAG_TILE_KILL,
     MaliFragTileKill},
    {"MaliNonFragActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_ACTIVE_CY,
     MaliNonFragActiveCy},
    {"MaliNonFragThread", protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_THREAD,
     MaliNonFragThread},
    {"MaliCoreActiveCy", protos::pbzero::ArmGpuCounters::MALI_CORE_ACTIVE_CY,
     MaliCoreActiveCy},
    {"MaliEngInstr", protos::pbzero::ArmGpuCounters::MALI_ENG_INSTR,
     MaliEngInstr},
    {"MaliLSIssueCy", protos::pbzero::ArmGpuCounters::MALI_LS_ISSUE_CY,
     MaliLSIssueCy},
    {"MaliTexInstr", protos::pbzero::ArmGpuCounters::MALI_TEX_INSTR,
     MaliTexInstr},
    {"MaliTexFiltIssueCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_FILT_ISSUE_CY,
     MaliTexFiltIssueCy},
    {"MaliLSRdHitCy", protos::pbzero::ArmGpuCounters::MALI_LS_RD_HIT_CY,
     MaliLSRdHitCy},
    {"MaliLSWrHitCy", protos::pbzero::ArmGpuCounters::MALI_LS_WR_HIT_CY,
     MaliLSWrHitCy},
    {"MaliGeomTrianglePrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_TRIANGLE_PRIM,
     MaliGeomTrianglePrim},
    {"MaliGeomPointPrim", protos::pbzero::ArmGpuCounters::MALI_GEOM_POINT_PRIM,
     MaliGeomPointPrim},
    {"MaliGeomLinePrim", protos::pbzero::ArmGpuCounters::MALI_GEOM_LINE_PRIM,
     MaliGeomLinePrim},
    {"MaliGeomFrontFacePrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_FRONT_FACE_PRIM,
     MaliGeomFrontFacePrim},
    {"MaliGeomBackFacePrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_BACK_FACE_PRIM,
     MaliGeomBackFacePrim},
    {"MaliGeomVisiblePrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_VISIBLE_PRIM,
     MaliGeomVisiblePrim},
    {"MaliGeomFaceXYPlaneCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_FACE_XY_PLANE_CULL_PRIM,
     MaliGeomFaceXYPlaneCullPrim},
    {"MaliGeomZPlaneCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_Z_PLANE_CULL_PRIM,
     MaliGeomZPlaneCullPrim},
    {"MaliTilerActiveCy", protos::pbzero::ArmGpuCounters::MALI_TILER_ACTIVE_CY,
     MaliTilerActiveCy},
    {"MaliGPUIRQUtil", protos::pbzero::ArmGpuCounters::MALI_GPUIRQ_UTIL,
     MaliGPUIRQUtil},
    {"MaliFragQueueUtil", protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_UTIL,
     MaliFragQueueUtil},
    {"MaliNonFragQueueUtil",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_UTIL,
     MaliNonFragQueueUtil},
    {"MaliExtBusRdBy", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_BY,
     MaliExtBusRdBy},
    {"MaliExtBusWrBy", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_BY,
     MaliExtBusWrBy},
    {"MaliExtBusRdStallRate",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_STALL_RATE,
     MaliExtBusRdStallRate},
    {"MaliExtBusWrStallRate",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_STALL_RATE,
     MaliExtBusWrStallRate},
    {"MaliTilerUtil", protos::pbzero::ArmGpuCounters::MALI_TILER_UTIL,
     MaliTilerUtil},
    {"MaliGeomTotalPrim", protos::pbzero::ArmGpuCounters::MALI_GEOM_TOTAL_PRIM,
     MaliGeomTotalPrim},
    {"MaliGeomVisibleRate",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_VISIBLE_RATE,
     MaliGeomVisibleRate},
    {"MaliGeomTotalCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_TOTAL_CULL_PRIM,
     MaliGeomTotalCullPrim},
    {"MaliGeomFaceXYPlaneCullRate",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_FACE_XY_PLANE_CULL_RATE,
     MaliGeomFaceXYPlaneCullRate},
    {"MaliGeomZPlaneCullRate",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_Z_PLANE_CULL_RATE,
     MaliGeomZPlaneCullRate},
    {"MaliNonFragUtil", protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_UTIL,
     MaliNonFragUtil},
    {"MaliNonFragThroughputCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_THROUGHPUT_CY,
     MaliNonFragThroughputCy},
    {"MaliFragUtil", protos::pbzero::ArmGpuCounters::MALI_FRAG_UTIL,
     MaliFragUtil},
    {"MaliFragThroughputCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_THROUGHPUT_CY,
     MaliFragThroughputCy},
    {"MaliFragHelpTdRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_HELP_TD_RATE,
     MaliFragHelpTdRate},
    {"MaliFragEZSTestRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_EZS_TEST_RATE,
     MaliFragEZSTestRate},
    {"MaliFragEZSKillRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_EZS_KILL_RATE,
     MaliFragEZSKillRate},
    {"MaliFragLZSTestRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_LZS_TEST_RATE,
     MaliFragLZSTestRate},
    {"MaliFragLZSKillRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_LZS_KILL_RATE,
     MaliFragLZSKillRate},
    {"MaliFragOverdraw", protos::pbzero::ArmGpuCounters::MALI_FRAG_OVERDRAW,
     MaliFragOverdraw},
    {"MaliFragTileKillRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_TILE_KILL_RATE,
     MaliFragTileKillRate},
    {"MaliCoreUtil", protos::pbzero::ArmGpuCounters::MALI_CORE_UTIL,
     MaliCoreUtil},
    {"MaliALUUtil", protos::pbzero::ArmGpuCounters::MALI_ALU_UTIL, MaliALUUtil},
    {"MaliTexSample", protos::pbzero::ArmGpuCounters::MALI_TEX_SAMPLE,
     MaliTexSample},
    {"MaliTexCPI", protos::pbzero::ArmGpuCounters::MALI_TEX_CPI, MaliTexCPI},
    {"MaliTexUtil", protos::pbzero::ArmGpuCounters::MALI_TEX_UTIL, MaliTexUtil},
    {"MaliTexIssueCy", protos::pbzero::ArmGpuCounters::MALI_TEX_ISSUE_CY,
     MaliTexIssueCy},
    {"MaliLSUtil", protos::pbzero::ArmGpuCounters::MALI_LS_UTIL, MaliLSUtil},
    {"MaliGPUPix", protos::pbzero::ArmGpuCounters::MALI_GPU_PIX, MaliGPUPix},
    {"MaliGPUCyPerPix", protos::pbzero::ArmGpuCounters::MALI_GPU_CY_PER_PIX,
     MaliGPUCyPerPix},
    {"MaliFragQueueWaitRdCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_WAIT_RD_CY,
     MaliFragQueueWaitRdCy},
    {"MaliFragQueueWaitIssueCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_WAIT_ISSUE_CY,
     MaliFragQueueWaitIssueCy},
    {"MaliFragQueueWaitDepCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_WAIT_DEP_CY,
     MaliFragQueueWaitDepCy},
    {"MaliFragQueueWaitFinishCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_WAIT_FINISH_CY,
     MaliFragQueueWaitFinishCy},
    {"MaliNonFragQueueWaitRdCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_WAIT_RD_CY,
     MaliNonFragQueueWaitRdCy},
    {"MaliNonFragQueueWaitIssueCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_WAIT_ISSUE_CY,
     MaliNonFragQueueWaitIssueCy},
    {"MaliNonFragQueueWaitDepCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_WAIT_DEP_CY,
     MaliNonFragQueueWaitDepCy},
    {"MaliNonFragQueueWaitFinishCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_WAIT_FINISH_CY,
     MaliNonFragQueueWaitFinishCy},
    {"MaliResQueueWaitRdCy",
     protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_WAIT_RD_CY,
     MaliResQueueWaitRdCy},
    {"MaliResQueueWaitIssueCy",
     protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_WAIT_ISSUE_CY,
     MaliResQueueWaitIssueCy},
    {"MaliResQueueWaitDepCy",
     protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_WAIT_DEP_CY,
     MaliResQueueWaitDepCy},
    {"MaliResQueueWaitFinishCy",
     protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_WAIT_FINISH_CY,
     MaliResQueueWaitFinishCy},
    {"MaliMMUL2Hit", protos::pbzero::ArmGpuCounters::MALI_MMUL2_HIT,
     MaliMMUL2Hit},
    {"MaliMMUL2Rd", protos::pbzero::ArmGpuCounters::MALI_MMUL2_RD, MaliMMUL2Rd},
    {"MaliMMULookup", protos::pbzero::ArmGpuCounters::MALI_MMU_LOOKUP,
     MaliMMULookup},
    {"MaliL2CacheLookup", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_LOOKUP,
     MaliL2CacheLookup},
    {"MaliL2CacheRdLookup",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_RD_LOOKUP,
     MaliL2CacheRdLookup},
    {"MaliL2CacheWrLookup",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_WR_LOOKUP,
     MaliL2CacheWrLookup},
    {"MaliFragFPKActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_FPK_ACTIVE_CY,
     MaliFragFPKActiveCy},
    {"MaliLSRdCy", protos::pbzero::ArmGpuCounters::MALI_LS_RD_CY, MaliLSRdCy},
    {"MaliLSWrCy", protos::pbzero::ArmGpuCounters::MALI_LS_WR_CY, MaliLSWrCy},
    {"MaliLSAtomic", protos::pbzero::ArmGpuCounters::MALI_LS_ATOMIC,
     MaliLSAtomic},
    {"MaliTilerPosCacheHit",
     protos::pbzero::ArmGpuCounters::MALI_TILER_POS_CACHE_HIT,
     MaliTilerPosCacheHit},
    {"MaliTilerPosCacheMiss",
     protos::pbzero::ArmGpuCounters::MALI_TILER_POS_CACHE_MISS,
     MaliTilerPosCacheMiss},
    {"MaliFragFPKBUtil", protos::pbzero::ArmGpuCounters::MALI_FRAG_FPKB_UTIL,
     MaliFragFPKBUtil},
    {"MaliFragQueueWaitFlushCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_WAIT_FLUSH_CY,
     MaliFragQueueWaitFlushCy},
    {"MaliNonFragQueueWaitFlushCy",
     protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_QUEUE_WAIT_FLUSH_CY,
     MaliNonFragQueueWaitFlushCy},
    {"MaliResQueueWaitFlushCy",
     protos::pbzero::ArmGpuCounters::MALI_RES_QUEUE_WAIT_FLUSH_CY,
     MaliResQueueWaitFlushCy},
    {"MaliL2CacheFlush", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_FLUSH,
     MaliL2CacheFlush},
    {"MaliGeomSampleCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_SAMPLE_CULL_PRIM,
     MaliGeomSampleCullPrim},
    {"MaliTilerRdBt", protos::pbzero::ArmGpuCounters::MALI_TILER_RD_BT,
     MaliTilerRdBt},
    {"MaliTilerWrBt", protos::pbzero::ArmGpuCounters::MALI_TILER_WR_BT,
     MaliTilerWrBt},
    {"MaliGeomPosShadTask",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_POS_SHAD_TASK,
     MaliGeomPosShadTask},
    {"MaliTilerPosShadStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TILER_POS_SHAD_STALL_CY,
     MaliTilerPosShadStallCy},
    {"MaliTilerPosShadFIFOFullCy",
     protos::pbzero::ArmGpuCounters::MALI_TILER_POS_SHAD_FIFO_FULL_CY,
     MaliTilerPosShadFIFOFullCy},
    {"MaliTilerVarCacheHit",
     protos::pbzero::ArmGpuCounters::MALI_TILER_VAR_CACHE_HIT,
     MaliTilerVarCacheHit},
    {"MaliTilerVarCacheMiss",
     protos::pbzero::ArmGpuCounters::MALI_TILER_VAR_CACHE_MISS,
     MaliTilerVarCacheMiss},
    {"MaliGeomVarShadTask",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_VAR_SHAD_TASK,
     MaliGeomVarShadTask},
    {"MaliTilerVarShadStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TILER_VAR_SHAD_STALL_CY,
     MaliTilerVarShadStallCy},
    {"MaliFragRastPrim", protos::pbzero::ArmGpuCounters::MALI_FRAG_RAST_PRIM,
     MaliFragRastPrim},
    {"MaliFragWarp", protos::pbzero::ArmGpuCounters::MALI_FRAG_WARP,
     MaliFragWarp},
    {"MaliFragPartWarp", protos::pbzero::ArmGpuCounters::MALI_FRAG_PART_WARP,
     MaliFragPartWarp},
    {"MaliFragEZSUpdateQd",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_EZS_UPDATE_QD,
     MaliFragEZSUpdateQd},
    {"MaliFragLZSTestQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_LZS_TEST_QD,
     MaliFragLZSTestQd},
    {"MaliFragLZSKillQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_LZS_KILL_QD,
     MaliFragLZSKillQd},
    {"MaliFragOpaqueQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_OPAQUE_QD,
     MaliFragOpaqueQd},
    {"MaliNonFragTask", protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_TASK,
     MaliNonFragTask},
    {"MaliNonFragWarp", protos::pbzero::ArmGpuCounters::MALI_NON_FRAG_WARP,
     MaliNonFragWarp},
    {"MaliEngActiveCy", protos::pbzero::ArmGpuCounters::MALI_ENG_ACTIVE_CY,
     MaliEngActiveCy},
    {"MaliEngDivergedInstr",
     protos::pbzero::ArmGpuCounters::MALI_ENG_DIVERGED_INSTR,
     MaliEngDivergedInstr},
    {"MaliEngStarveCy", protos::pbzero::ArmGpuCounters::MALI_ENG_STARVE_CY,
     MaliEngStarveCy},
    {"MaliTexQuads", protos::pbzero::ArmGpuCounters::MALI_TEX_QUADS,
     MaliTexQuads},
    {"MaliTexQuadPass", protos::pbzero::ArmGpuCounters::MALI_TEX_QUAD_PASS,
     MaliTexQuadPass},
    {"MaliTexQuadPassDescMiss",
     protos::pbzero::ArmGpuCounters::MALI_TEX_QUAD_PASS_DESC_MISS,
     MaliTexQuadPassDescMiss},
    {"MaliTexQuadPassMip",
     protos::pbzero::ArmGpuCounters::MALI_TEX_QUAD_PASS_MIP,
     MaliTexQuadPassMip},
    {"MaliTexQuadPassTri",
     protos::pbzero::ArmGpuCounters::MALI_TEX_QUAD_PASS_TRI,
     MaliTexQuadPassTri},
    {"MaliTexCacheFetch", protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_FETCH,
     MaliTexCacheFetch},
    {"MaliTexCacheCompressFetch",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_COMPRESS_FETCH,
     MaliTexCacheCompressFetch},
    {"MaliTexCacheLookup",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_LOOKUP, MaliTexCacheLookup},
    {"MaliLSFullRd", protos::pbzero::ArmGpuCounters::MALI_LS_FULL_RD,
     MaliLSFullRd},
    {"MaliLSPartRd", protos::pbzero::ArmGpuCounters::MALI_LS_PART_RD,
     MaliLSPartRd},
    {"MaliLSFullWr", protos::pbzero::ArmGpuCounters::MALI_LS_FULL_WR,
     MaliLSFullWr},
    {"MaliLSPartWr", protos::pbzero::ArmGpuCounters::MALI_LS_PART_WR,
     MaliLSPartWr},
    {"MaliVarInstr", protos::pbzero::ArmGpuCounters::MALI_VAR_INSTR,
     MaliVarInstr},
    {"MaliVar32IssueSlot",
     protos::pbzero::ArmGpuCounters::MALI_VAR32_ISSUE_SLOT, MaliVar32IssueSlot},
    {"MaliVar16IssueSlot",
     protos::pbzero::ArmGpuCounters::MALI_VAR16_ISSUE_SLOT, MaliVar16IssueSlot},
    {"MaliAttrInstr", protos::pbzero::ArmGpuCounters::MALI_ATTR_INSTR,
     MaliAttrInstr},
    {"MaliSCBusFFEL2RdBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_FFEL2_RD_BT,
     MaliSCBusFFEL2RdBt},
    {"MaliSCBusFFEExtRdBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_FFE_EXT_RD_BT,
     MaliSCBusFFEExtRdBt},
    {"MaliSCBusLSL2RdBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LSL2_RD_BT, MaliSCBusLSL2RdBt},
    {"MaliSCBusLSExtRdBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LS_EXT_RD_BT,
     MaliSCBusLSExtRdBt},
    {"MaliSCBusTexL2RdBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TEX_L2_RD_BT,
     MaliSCBusTexL2RdBt},
    {"MaliSCBusTexExtRdBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TEX_EXT_RD_BT,
     MaliSCBusTexExtRdBt},
    {"MaliSCBusOtherL2RdBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_OTHER_L2_RD_BT,
     MaliSCBusOtherL2RdBt},
    {"MaliSCBusLSWBWrBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LSWB_WR_BT, MaliSCBusLSWBWrBt},
    {"MaliSCBusTileWrBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TILE_WR_BT, MaliSCBusTileWrBt},
    {"MaliSCBusLSOtherWrBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LS_OTHER_WR_BT,
     MaliSCBusLSOtherWrBt},
    {"MaliMMUL3Rd", protos::pbzero::ArmGpuCounters::MALI_MMUL3_RD, MaliMMUL3Rd},
    {"MaliMMUL3Hit", protos::pbzero::ArmGpuCounters::MALI_MMUL3_HIT,
     MaliMMUL3Hit},
    {"MaliMMUS2Lookup", protos::pbzero::ArmGpuCounters::MALI_MMUS2_LOOKUP,
     MaliMMUS2Lookup},
    {"MaliMMUS2L3Rd", protos::pbzero::ArmGpuCounters::MALI_MMUS2L3_RD,
     MaliMMUS2L3Rd},
    {"MaliMMUS2L2Rd", protos::pbzero::ArmGpuCounters::MALI_MMUS2L2_RD,
     MaliMMUS2L2Rd},
    {"MaliMMUS2L3Hit", protos::pbzero::ArmGpuCounters::MALI_MMUS2L3_HIT,
     MaliMMUS2L3Hit},
    {"MaliMMUS2L2Hit", protos::pbzero::ArmGpuCounters::MALI_MMUS2L2_HIT,
     MaliMMUS2L2Hit},
    {"MaliL2CacheRd", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_RD,
     MaliL2CacheRd},
    {"MaliL2CacheRdStallCy",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_RD_STALL_CY,
     MaliL2CacheRdStallCy},
    {"MaliL2CacheWr", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_WR,
     MaliL2CacheWr},
    {"MaliL2CacheWrStallCy",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_WR_STALL_CY,
     MaliL2CacheWrStallCy},
    {"MaliL2CacheSnp", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_SNP,
     MaliL2CacheSnp},
    {"MaliL2CacheSnpStallCy",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_SNP_STALL_CY,
     MaliL2CacheSnpStallCy},
    {"MaliL2CacheL1Rd", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_L1_RD,
     MaliL2CacheL1Rd},
    {"MaliL2CacheL1RdStallCy",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_L1_RD_STALL_CY,
     MaliL2CacheL1RdStallCy},
    {"MaliL2CacheL1Wr", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_L1_WR,
     MaliL2CacheL1Wr},
    {"MaliL2CacheSnpLookup",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_SNP_LOOKUP,
     MaliL2CacheSnpLookup},
    {"MaliExtBusRd", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD,
     MaliExtBusRd},
    {"MaliExtBusRdNoSnoop",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_NO_SNOOP,
     MaliExtBusRdNoSnoop},
    {"MaliExtBusRdUnique",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_UNIQUE,
     MaliExtBusRdUnique},
    {"MaliExtBusRdOTQ1", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_OTQ1,
     MaliExtBusRdOTQ1},
    {"MaliExtBusRdOTQ2", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_OTQ2,
     MaliExtBusRdOTQ2},
    {"MaliExtBusRdOTQ3", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_OTQ3,
     MaliExtBusRdOTQ3},
    {"MaliExtBusRdLat0", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_LAT0,
     MaliExtBusRdLat0},
    {"MaliExtBusRdLat128",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_LAT128,
     MaliExtBusRdLat128},
    {"MaliExtBusRdLat192",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_LAT192,
     MaliExtBusRdLat192},
    {"MaliExtBusRdLat256",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_LAT256,
     MaliExtBusRdLat256},
    {"MaliExtBusRdLat320",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_LAT320,
     MaliExtBusRdLat320},
    {"MaliExtBusWr", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR,
     MaliExtBusWr},
    {"MaliExtBusWrNoSnoopFull",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_NO_SNOOP_FULL,
     MaliExtBusWrNoSnoopFull},
    {"MaliExtBusWrNoSnoopPart",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_NO_SNOOP_PART,
     MaliExtBusWrNoSnoopPart},
    {"MaliExtBusWrSnoopFull",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_SNOOP_FULL,
     MaliExtBusWrSnoopFull},
    {"MaliExtBusWrSnoopPart",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_SNOOP_PART,
     MaliExtBusWrSnoopPart},
    {"MaliExtBusWrOTQ1", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_OTQ1,
     MaliExtBusWrOTQ1},
    {"MaliExtBusWrOTQ2", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_OTQ2,
     MaliExtBusWrOTQ2},
    {"MaliExtBusWrOTQ3", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_OTQ3,
     MaliExtBusWrOTQ3},
    {"MaliL2CacheIncSnp", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_INC_SNP,
     MaliL2CacheIncSnp},
    {"MaliL2CacheIncSnpStallCy",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_INC_SNP_STALL_CY,
     MaliL2CacheIncSnpStallCy},
    {"MaliL2CacheRdMissRate",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_RD_MISS_RATE,
     MaliL2CacheRdMissRate},
    {"MaliL2CacheWrMissRate",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_WR_MISS_RATE,
     MaliL2CacheWrMissRate},
    {"MaliExtBusRdLat384",
     protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_LAT384,
     MaliExtBusRdLat384},
    {"MaliExtBusRdOTQ4", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_RD_OTQ4,
     MaliExtBusRdOTQ4},
    {"MaliExtBusWrOTQ4", protos::pbzero::ArmGpuCounters::MALI_EXT_BUS_WR_OTQ4,
     MaliExtBusWrOTQ4},
    {"MaliGeomSampleCullRate",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_SAMPLE_CULL_RATE,
     MaliGeomSampleCullRate},
    {"MaliGeomPosShadThread",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_POS_SHAD_THREAD,
     MaliGeomPosShadThread},
    {"MaliGeomPosShadThreadPerPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_POS_SHAD_THREAD_PER_PRIM,
     MaliGeomPosShadThreadPerPrim},
    {"MaliTilerPosCacheHitRate",
     protos::pbzero::ArmGpuCounters::MALI_TILER_POS_CACHE_HIT_RATE,
     MaliTilerPosCacheHitRate},
    {"MaliGeomVarShadThread",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_VAR_SHAD_THREAD,
     MaliGeomVarShadThread},
    {"MaliGeomVarShadThreadPerPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_VAR_SHAD_THREAD_PER_PRIM,
     MaliGeomVarShadThreadPerPrim},
    {"MaliTilerVarCacheHitRate",
     protos::pbzero::ArmGpuCounters::MALI_TILER_VAR_CACHE_HIT_RATE,
     MaliTilerVarCacheHitRate},
    {"MaliFragOpaqueQdRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_OPAQUE_QD_RATE,
     MaliFragOpaqueQdRate},
    {"MaliFragTransparentQd",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_TRANSPARENT_QD,
     MaliFragTransparentQd},
    {"MaliFragShadedQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_SHADED_QD,
     MaliFragShadedQd},
    {"MaliFragPartWarpRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PART_WARP_RATE,
     MaliFragPartWarpRate},
    {"MaliFragEZSUpdateRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_EZS_UPDATE_RATE,
     MaliFragEZSUpdateRate},
    {"MaliFragFPKKillQd", protos::pbzero::ArmGpuCounters::MALI_FRAG_FPK_KILL_QD,
     MaliFragFPKKillQd},
    {"MaliFragFPKKillRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_FPK_KILL_RATE,
     MaliFragFPKKillRate},
    {"MaliEngDivergedInstrRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_DIVERGED_INSTR_RATE,
     MaliEngDivergedInstrRate},
    {"MaliTexCacheUtil", protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_UTIL,
     MaliTexCacheUtil},
    {"MaliTexMipInstrRate",
     protos::pbzero::ArmGpuCounters::MALI_TEX_MIP_INSTR_RATE,
     MaliTexMipInstrRate},
    {"MaliTexCacheCompressFetchRate",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_COMPRESS_FETCH_RATE,
     MaliTexCacheCompressFetchRate},
    {"MaliTexTriInstrRate",
     protos::pbzero::ArmGpuCounters::MALI_TEX_TRI_INSTR_RATE,
     MaliTexTriInstrRate},
    {"MaliVar32IssueCy", protos::pbzero::ArmGpuCounters::MALI_VAR32_ISSUE_CY,
     MaliVar32IssueCy},
    {"MaliVar16IssueCy", protos::pbzero::ArmGpuCounters::MALI_VAR16_ISSUE_CY,
     MaliVar16IssueCy},
    {"MaliVarIssueCy", protos::pbzero::ArmGpuCounters::MALI_VAR_ISSUE_CY,
     MaliVarIssueCy},
    {"MaliVarUtil", protos::pbzero::ArmGpuCounters::MALI_VAR_UTIL, MaliVarUtil},
    {"MaliSCBusFFEL2RdBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_FFEL2_RD_BY,
     MaliSCBusFFEL2RdBy},
    {"MaliSCBusFFEExtRdBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_FFE_EXT_RD_BY,
     MaliSCBusFFEExtRdBy},
    {"MaliSCBusLSL2RdBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LSL2_RD_BY, MaliSCBusLSL2RdBy},
    {"MaliSCBusLSL2RdByPerRd",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LSL2_RD_BY_PER_RD,
     MaliSCBusLSL2RdByPerRd},
    {"MaliSCBusLSExtRdBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LS_EXT_RD_BY,
     MaliSCBusLSExtRdBy},
    {"MaliSCBusLSExtRdByPerRd",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LS_EXT_RD_BY_PER_RD,
     MaliSCBusLSExtRdByPerRd},
    {"MaliSCBusTexL2RdBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TEX_L2_RD_BY,
     MaliSCBusTexL2RdBy},
    {"MaliSCBusTexL2RdByPerRd",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TEX_L2_RD_BY_PER_RD,
     MaliSCBusTexL2RdByPerRd},
    {"MaliSCBusTexExtRdBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TEX_EXT_RD_BY,
     MaliSCBusTexExtRdBy},
    {"MaliSCBusTexExtRdByPerRd",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TEX_EXT_RD_BY_PER_RD,
     MaliSCBusTexExtRdByPerRd},
    {"MaliSCBusLSWrBt", protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LS_WR_BT,
     MaliSCBusLSWrBt},
    {"MaliSCBusLSWrBy", protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LS_WR_BY,
     MaliSCBusLSWrBy},
    {"MaliSCBusLSWrByPerWr",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_LS_WR_BY_PER_WR,
     MaliSCBusLSWrByPerWr},
    {"MaliSCBusTileWrBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_TILE_WR_BY, MaliSCBusTileWrBy},
    {"MaliCoreAllRegsWarp",
     protos::pbzero::ArmGpuCounters::MALI_CORE_ALL_REGS_WARP,
     MaliCoreAllRegsWarp},
    {"MaliCoreFullWarp", protos::pbzero::ArmGpuCounters::MALI_CORE_FULL_WARP,
     MaliCoreFullWarp},
    {"MaliCoreAllRegsWarpRate",
     protos::pbzero::ArmGpuCounters::MALI_CORE_ALL_REGS_WARP_RATE,
     MaliCoreAllRegsWarpRate},
    {"MaliCoreFullWarpRate",
     protos::pbzero::ArmGpuCounters::MALI_CORE_FULL_WARP_RATE,
     MaliCoreFullWarpRate},
    {"MaliTexMipInstr", protos::pbzero::ArmGpuCounters::MALI_TEX_MIP_INSTR,
     MaliTexMipInstr},
    {"MaliTexCompressInstr",
     protos::pbzero::ArmGpuCounters::MALI_TEX_COMPRESS_INSTR,
     MaliTexCompressInstr},
    {"MaliTex3DInstr", protos::pbzero::ArmGpuCounters::MALI_TEX3D_INSTR,
     MaliTex3DInstr},
    {"MaliTexTriInstr", protos::pbzero::ArmGpuCounters::MALI_TEX_TRI_INSTR,
     MaliTexTriInstr},
    {"MaliTexCoordStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_COORD_STALL_CY,
     MaliTexCoordStallCy},
    {"MaliTexDataStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_DATA_STALL_CY,
     MaliTexDataStallCy},
    {"MaliTexPartDataStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_PART_DATA_STALL_CY,
     MaliTexPartDataStallCy},
    {"MaliSCBusOtherWrBt",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_OTHER_WR_BT,
     MaliSCBusOtherWrBt},
    {"MaliTexCompressInstrRate",
     protos::pbzero::ArmGpuCounters::MALI_TEX_COMPRESS_INSTR_RATE,
     MaliTexCompressInstrRate},
    {"MaliTex3DInstrRate",
     protos::pbzero::ArmGpuCounters::MALI_TEX3D_INSTR_RATE, MaliTex3DInstrRate},
    {"MaliSCBusOtherWrBy",
     protos::pbzero::ArmGpuCounters::MALI_SC_BUS_OTHER_WR_BY,
     MaliSCBusOtherWrBy},
    {"MaliFragRastPartQd",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_RAST_PART_QD,
     MaliFragRastPartQd},
    {"MaliEngFMAInstr", protos::pbzero::ArmGpuCounters::MALI_ENG_FMA_INSTR,
     MaliEngFMAInstr},
    {"MaliEngCVTInstr", protos::pbzero::ArmGpuCounters::MALI_ENG_CVT_INSTR,
     MaliEngCVTInstr},
    {"MaliEngSFUInstr", protos::pbzero::ArmGpuCounters::MALI_ENG_SFU_INSTR,
     MaliEngSFUInstr},
    {"MaliEngICacheMiss", protos::pbzero::ArmGpuCounters::MALI_ENG_I_CACHE_MISS,
     MaliEngICacheMiss},
    {"MaliEngSWBlendInstr",
     protos::pbzero::ArmGpuCounters::MALI_ENG_SW_BLEND_INSTR,
     MaliEngSWBlendInstr},
    {"MaliTexInBt", protos::pbzero::ArmGpuCounters::MALI_TEX_IN_BT,
     MaliTexInBt},
    {"MaliTexDescStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_DESC_STALL_CY,
     MaliTexDescStallCy},
    {"MaliTexDataFetchStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_DATA_FETCH_STALL_CY,
     MaliTexDataFetchStallCy},
    {"MaliTexFiltStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_FILT_STALL_CY,
     MaliTexFiltStallCy},
    {"MaliTexFullBiFiltCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_FULL_BI_FILT_CY,
     MaliTexFullBiFiltCy},
    {"MaliTexFullTriFiltCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_FULL_TRI_FILT_CY,
     MaliTexFullTriFiltCy},
    {"MaliTexOutMsg", protos::pbzero::ArmGpuCounters::MALI_TEX_OUT_MSG,
     MaliTexOutMsg},
    {"MaliTexOutBt", protos::pbzero::ArmGpuCounters::MALI_TEX_OUT_BT,
     MaliTexOutBt},
    {"MaliFragRastPartQdRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_RAST_PART_QD_RATE,
     MaliFragRastPartQdRate},
    {"MaliEngFMAPipeUtil",
     protos::pbzero::ArmGpuCounters::MALI_ENG_FMA_PIPE_UTIL,
     MaliEngFMAPipeUtil},
    {"MaliEngCVTPipeUtil",
     protos::pbzero::ArmGpuCounters::MALI_ENG_CVT_PIPE_UTIL,
     MaliEngCVTPipeUtil},
    {"MaliEngSFUPipeUtil",
     protos::pbzero::ArmGpuCounters::MALI_ENG_SFU_PIPE_UTIL,
     MaliEngSFUPipeUtil},
    {"MaliEngArithInstr", protos::pbzero::ArmGpuCounters::MALI_ENG_ARITH_INSTR,
     MaliEngArithInstr},
    {"MaliEngSWBlendRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_SW_BLEND_RATE,
     MaliEngSWBlendRate},
    {"MaliTexInBusUtil", protos::pbzero::ArmGpuCounters::MALI_TEX_IN_BUS_UTIL,
     MaliTexInBusUtil},
    {"MaliTexOutBusUtil", protos::pbzero::ArmGpuCounters::MALI_TEX_OUT_BUS_UTIL,
     MaliTexOutBusUtil},
    {"MaliTexFiltFullRate",
     protos::pbzero::ArmGpuCounters::MALI_TEX_FILT_FULL_RATE,
     MaliTexFiltFullRate},
    {"MaliAnyActiveCy", protos::pbzero::ArmGpuCounters::MALI_ANY_ACTIVE_CY,
     MaliAnyActiveCy},
    {"MaliAnyUtil", protos::pbzero::ArmGpuCounters::MALI_ANY_UTIL, MaliAnyUtil},
    {"MaliCSFMCUActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFMCU_ACTIVE_CY, MaliCSFMCUActiveCy},
    {"MaliGPUQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_GPU_QUEUE_ACTIVE_CY,
     MaliGPUQueueActiveCy},
    {"MaliGPUIRQ", protos::pbzero::ArmGpuCounters::MALI_GPUIRQ, MaliGPUIRQ},
    {"MaliL2CacheFlushCy",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_FLUSH_CY,
     MaliL2CacheFlushCy},
    {"MaliVertQueuedCy", protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUED_CY,
     MaliVertQueuedCy},
    {"MaliVertQueueJob", protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUE_JOB,
     MaliVertQueueJob},
    {"MaliVertQueueTask", protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUE_TASK,
     MaliVertQueueTask},
    {"MaliVertQueueTotalActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUE_TOTAL_ACTIVE_CY,
     MaliVertQueueTotalActiveCy},
    {"MaliVertQueueIRQActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUE_IRQ_ACTIVE_CY,
     MaliVertQueueIRQActiveCy},
    {"MaliVertQueueAssignStallCy",
     protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUE_ASSIGN_STALL_CY,
     MaliVertQueueAssignStallCy},
    {"MaliTilerQueueDrainStallCy",
     protos::pbzero::ArmGpuCounters::MALI_TILER_QUEUE_DRAIN_STALL_CY,
     MaliTilerQueueDrainStallCy},
    {"MaliCompQueuedCy", protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUED_CY,
     MaliCompQueuedCy},
    {"MaliCompQueueJob", protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_JOB,
     MaliCompQueueJob},
    {"MaliCompQueueTask", protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_TASK,
     MaliCompQueueTask},
    {"MaliCompQueueTotalActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_TOTAL_ACTIVE_CY,
     MaliCompQueueTotalActiveCy},
    {"MaliCompQueueIRQActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_IRQ_ACTIVE_CY,
     MaliCompQueueIRQActiveCy},
    {"MaliCompQueueAssignStallCy",
     protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_ASSIGN_STALL_CY,
     MaliCompQueueAssignStallCy},
    {"MaliCompQueueDrainStallCy",
     protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_DRAIN_STALL_CY,
     MaliCompQueueDrainStallCy},
    {"MaliFragQueuedCy", protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUED_CY,
     MaliFragQueuedCy},
    {"MaliFragQueueTotalActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_TOTAL_ACTIVE_CY,
     MaliFragQueueTotalActiveCy},
    {"MaliFragQueueIRQActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_IRQ_ACTIVE_CY,
     MaliFragQueueIRQActiveCy},
    {"MaliFragQueueAssignStallCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_QUEUE_ASSIGN_STALL_CY,
     MaliFragQueueAssignStallCy},
    {"MaliCSFCEUActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFCEU_ACTIVE_CY, MaliCSFCEUActiveCy},
    {"MaliCSFLSUActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFLSU_ACTIVE_CY, MaliCSFLSUActiveCy},
    {"MaliCSFCS0ActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFCS0_ACTIVE_CY, MaliCSFCS0ActiveCy},
    {"MaliCS0WaitStallCy",
     protos::pbzero::ArmGpuCounters::MALI_CS0_WAIT_STALL_CY,
     MaliCS0WaitStallCy},
    {"MaliCSFCS1ActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFCS1_ACTIVE_CY, MaliCSFCS1ActiveCy},
    {"MaliCS1WaitStallCy",
     protos::pbzero::ArmGpuCounters::MALI_CS1_WAIT_STALL_CY,
     MaliCS1WaitStallCy},
    {"MaliCSFCS2ActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFCS2_ACTIVE_CY, MaliCSFCS2ActiveCy},
    {"MaliCS2WaitStallCy",
     protos::pbzero::ArmGpuCounters::MALI_CS2_WAIT_STALL_CY,
     MaliCS2WaitStallCy},
    {"MaliCSFCS3ActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFCS3_ACTIVE_CY, MaliCSFCS3ActiveCy},
    {"MaliCS3WaitStallCy",
     protos::pbzero::ArmGpuCounters::MALI_CS3_WAIT_STALL_CY,
     MaliCS3WaitStallCy},
    {"MaliL2CacheEvict", protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_EVICT,
     MaliL2CacheEvict},
    {"MaliL2CacheCleanUnique",
     protos::pbzero::ArmGpuCounters::MALI_L2_CACHE_CLEAN_UNIQUE,
     MaliL2CacheCleanUnique},
    {"MaliVertQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUE_ACTIVE_CY,
     MaliVertQueueActiveCy},
    {"MaliVertQueueUtil", protos::pbzero::ArmGpuCounters::MALI_VERT_QUEUE_UTIL,
     MaliVertQueueUtil},
    {"MaliCompQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_ACTIVE_CY,
     MaliCompQueueActiveCy},
    {"MaliCompQueueUtil", protos::pbzero::ArmGpuCounters::MALI_COMP_QUEUE_UTIL,
     MaliCompQueueUtil},
    {"MaliCSFMCUUtil", protos::pbzero::ArmGpuCounters::MALI_CSFMCU_UTIL,
     MaliCSFMCUUtil},
    {"MaliCSFLSUUtil", protos::pbzero::ArmGpuCounters::MALI_CSFLSU_UTIL,
     MaliCSFLSUUtil},
    {"MaliCSFCEUUtil", protos::pbzero::ArmGpuCounters::MALI_CSFCEU_UTIL,
     MaliCSFCEUUtil},
    {"MaliGPUActive2Cy", protos::pbzero::ArmGpuCounters::MALI_GPU_ACTIVE2_CY,
     MaliGPUActive2Cy},
    {"MaliEngNarrowInstr",
     protos::pbzero::ArmGpuCounters::MALI_ENG_NARROW_INSTR, MaliEngNarrowInstr},
    {"MaliFragRastCoarseQd",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_RAST_COARSE_QD,
     MaliFragRastCoarseQd},
    {"MaliRTUTri", protos::pbzero::ArmGpuCounters::MALI_RTU_TRI, MaliRTUTri},
    {"MaliRTUBox", protos::pbzero::ArmGpuCounters::MALI_RTU_BOX, MaliRTUBox},
    {"MaliRTUTriBin1", protos::pbzero::ArmGpuCounters::MALI_RTU_TRI_BIN1,
     MaliRTUTriBin1},
    {"MaliRTUTriBin5", protos::pbzero::ArmGpuCounters::MALI_RTU_TRI_BIN5,
     MaliRTUTriBin5},
    {"MaliRTUTriBin9", protos::pbzero::ArmGpuCounters::MALI_RTU_TRI_BIN9,
     MaliRTUTriBin9},
    {"MaliRTUTriBin13", protos::pbzero::ArmGpuCounters::MALI_RTU_TRI_BIN13,
     MaliRTUTriBin13},
    {"MaliRTUBoxBin1", protos::pbzero::ArmGpuCounters::MALI_RTU_BOX_BIN1,
     MaliRTUBoxBin1},
    {"MaliRTUBoxBin5", protos::pbzero::ArmGpuCounters::MALI_RTU_BOX_BIN5,
     MaliRTUBoxBin5},
    {"MaliRTUBoxBin9", protos::pbzero::ArmGpuCounters::MALI_RTU_BOX_BIN9,
     MaliRTUBoxBin9},
    {"MaliRTUBoxBin13", protos::pbzero::ArmGpuCounters::MALI_RTU_BOX_BIN13,
     MaliRTUBoxBin13},
    {"MaliRTUOpaqueHit", protos::pbzero::ArmGpuCounters::MALI_RTU_OPAQUE_HIT,
     MaliRTUOpaqueHit},
    {"MaliRTUNonOpaqueHit",
     protos::pbzero::ArmGpuCounters::MALI_RTU_NON_OPAQUE_HIT,
     MaliRTUNonOpaqueHit},
    {"MaliRTUFirstHitTerm",
     protos::pbzero::ArmGpuCounters::MALI_RTU_FIRST_HIT_TERM,
     MaliRTUFirstHitTerm},
    {"MaliRTUMiss", protos::pbzero::ArmGpuCounters::MALI_RTU_MISS, MaliRTUMiss},
    {"MaliRTURay", protos::pbzero::ArmGpuCounters::MALI_RTU_RAY, MaliRTURay},
    {"MaliRTUBoxIssueCy", protos::pbzero::ArmGpuCounters::MALI_RTU_BOX_ISSUE_CY,
     MaliRTUBoxIssueCy},
    {"MaliRTUTriIssueCy", protos::pbzero::ArmGpuCounters::MALI_RTU_TRI_ISSUE_CY,
     MaliRTUTriIssueCy},
    {"MaliGeomFaceCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_FACE_CULL_PRIM,
     MaliGeomFaceCullPrim},
    {"MaliGeomPlaneCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_PLANE_CULL_PRIM,
     MaliGeomPlaneCullPrim},
    {"MaliGeomFaceCullRate",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_FACE_CULL_RATE,
     MaliGeomFaceCullRate},
    {"MaliGeomPlaneCullRate",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_PLANE_CULL_RATE,
     MaliGeomPlaneCullRate},
    {"MaliFragShadRate", protos::pbzero::ArmGpuCounters::MALI_FRAG_SHAD_RATE,
     MaliFragShadRate},
    {"MaliCoreFragWarpOcc",
     protos::pbzero::ArmGpuCounters::MALI_CORE_FRAG_WARP_OCC,
     MaliCoreFragWarpOcc},
    {"MaliEngNarrowInstrRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_NARROW_INSTR_RATE,
     MaliEngNarrowInstrRate},
    {"MaliRTUUtil", protos::pbzero::ArmGpuCounters::MALI_RTU_UTIL, MaliRTUUtil},
    {"MaliBinningQueuedCy",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUED_CY,
     MaliBinningQueuedCy},
    {"MaliBinningQueueJob",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUE_JOB,
     MaliBinningQueueJob},
    {"MaliBinningQueueTask",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUE_TASK,
     MaliBinningQueueTask},
    {"MaliBinningQueueIRQActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUE_IRQ_ACTIVE_CY,
     MaliBinningQueueIRQActiveCy},
    {"MaliBinningQueueAssignStallCy",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUE_ASSIGN_STALL_CY,
     MaliBinningQueueAssignStallCy},
    {"MaliMainQueuedCy", protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUED_CY,
     MaliMainQueuedCy},
    {"MaliMainQueueJob", protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUE_JOB,
     MaliMainQueueJob},
    {"MaliMainQueueTask", protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUE_TASK,
     MaliMainQueueTask},
    {"MaliMainQueueIRQActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUE_IRQ_ACTIVE_CY,
     MaliMainQueueIRQActiveCy},
    {"MaliMainQueueAssignStallCy",
     protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUE_ASSIGN_STALL_CY,
     MaliMainQueueAssignStallCy},
    {"MaliMainActiveCy", protos::pbzero::ArmGpuCounters::MALI_MAIN_ACTIVE_CY,
     MaliMainActiveCy},
    {"MaliCompOrBinningActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_COMP_OR_BINNING_ACTIVE_CY,
     MaliCompOrBinningActiveCy},
    {"MaliTexL1CacheLoadCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_L1_CACHE_LOAD_CY,
     MaliTexL1CacheLoadCy},
    {"MaliTexCacheSimpleLoadCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_SIMPLE_LOAD_CY,
     MaliTexCacheSimpleLoadCy},
    {"MaliTexL1CacheOutputCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_L1_CACHE_OUTPUT_CY,
     MaliTexL1CacheOutputCy},
    {"MaliTexL1CacheLookupCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_L1_CACHE_LOOKUP_CY,
     MaliTexL1CacheLookupCy},
    {"MaliTexOutSingleMsg",
     protos::pbzero::ArmGpuCounters::MALI_TEX_OUT_SINGLE_MSG,
     MaliTexOutSingleMsg},
    {"MaliTexCacheLookupCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_LOOKUP_CY,
     MaliTexCacheLookupCy},
    {"MaliTexCacheComplexLoadCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CACHE_COMPLEX_LOAD_CY,
     MaliTexCacheComplexLoadCy},
    {"MaliTexIndexCy", protos::pbzero::ArmGpuCounters::MALI_TEX_INDEX_CY,
     MaliTexIndexCy},
    {"MaliTexClkStarvedCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CLK_STARVED_CY,
     MaliTexClkStarvedCy},
    {"MaliTexClkActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_TEX_CLK_ACTIVE_CY,
     MaliTexClkActiveCy},
    {"MaliGeomScissorCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_SCISSOR_CULL_PRIM,
     MaliGeomScissorCullPrim},
    {"MaliGeomVisibleDVSPrim",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_VISIBLE_DVS_PRIM,
     MaliGeomVisibleDVSPrim},
    {"MaliMainQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUE_ACTIVE_CY,
     MaliMainQueueActiveCy},
    {"MaliMainQueueUtil", protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUE_UTIL,
     MaliMainQueueUtil},
    {"MaliBinningQueueActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUE_ACTIVE_CY,
     MaliBinningQueueActiveCy},
    {"MaliBinningQueueUtil",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUE_UTIL,
     MaliBinningQueueUtil},
    {"MaliGeomScissorCullRate",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_SCISSOR_CULL_RATE,
     MaliGeomScissorCullRate},
    {"MaliCompOrBinningUtil",
     protos::pbzero::ArmGpuCounters::MALI_COMP_OR_BINNING_UTIL,
     MaliCompOrBinningUtil},
    {"MaliMainUtil", protos::pbzero::ArmGpuCounters::MALI_MAIN_UTIL,
     MaliMainUtil},
    {"MaliCSDoorbellIRQCy",
     protos::pbzero::ArmGpuCounters::MALI_CS_DOORBELL_IRQ_CY,
     MaliCSDoorbellIRQCy},
    {"MaliMainQueueTotalActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_MAIN_QUEUE_TOTAL_ACTIVE_CY,
     MaliMainQueueTotalActiveCy},
    {"MaliBinningQueueTotalActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_BINNING_QUEUE_TOTAL_ACTIVE_CY,
     MaliBinningQueueTotalActiveCy},
    {"MaliCSFCS4ActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFCS4_ACTIVE_CY, MaliCSFCS4ActiveCy},
    {"MaliCS4WaitStallCy",
     protos::pbzero::ArmGpuCounters::MALI_CS4_WAIT_STALL_CY,
     MaliCS4WaitStallCy},
    {"MaliCSFCS5ActiveCy",
     protos::pbzero::ArmGpuCounters::MALI_CSFCS5_ACTIVE_CY, MaliCSFCS5ActiveCy},
    {"MaliCS5WaitStallCy",
     protos::pbzero::ArmGpuCounters::MALI_CS5_WAIT_STALL_CY,
     MaliCS5WaitStallCy},
    {"MaliFragPrim", protos::pbzero::ArmGpuCounters::MALI_FRAG_PRIM,
     MaliFragPrim},
    {"MaliFragPrepassCullPrim",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_CULL_PRIM,
     MaliFragPrepassCullPrim},
    {"MaliFragPrepassPrim",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_PRIM,
     MaliFragPrepassPrim},
    {"MaliFragPrepassUncullPrim",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_UNCULL_PRIM,
     MaliFragPrepassUncullPrim},
    {"MaliFragPrepassEZSUpdateQd",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_EZS_UPDATE_QD,
     MaliFragPrepassEZSUpdateQd},
    {"MaliFragPrepassTestQd",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_TEST_QD,
     MaliFragPrepassTestQd},
    {"MaliFragPrepassKillQd",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_KILL_QD,
     MaliFragPrepassKillQd},
    {"MaliFragPrepassWarp",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_WARP,
     MaliFragPrepassWarp},
    {"MaliFragMainPassStallCy",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_MAIN_PASS_STALL_CY,
     MaliFragMainPassStallCy},
    {"MaliDefVertWarp", protos::pbzero::ArmGpuCounters::MALI_DEF_VERT_WARP,
     MaliDefVertWarp},
    {"MaliEngTexBackpressureCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_TEX_BACKPRESSURE_CY,
     MaliEngTexBackpressureCy},
    {"MaliEngVarBackpressureCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_VAR_BACKPRESSURE_CY,
     MaliEngVarBackpressureCy},
    {"MaliEngBlendBackpressureCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_BLEND_BACKPRESSURE_CY,
     MaliEngBlendBackpressureCy},
    {"MaliEngZSBackpressureCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_ZS_BACKPRESSURE_CY,
     MaliEngZSBackpressureCy},
    {"MaliEngLSBackpressureCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_LS_BACKPRESSURE_CY,
     MaliEngLSBackpressureCy},
    {"MaliEngAttrBackpressureCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_ATTR_BACKPRESSURE_CY,
     MaliEngAttrBackpressureCy},
    {"MaliEngSlot1IssueCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_SLOT1_ISSUE_CY,
     MaliEngSlot1IssueCy},
    {"MaliEngSlotAnyIssueCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_SLOT_ANY_ISSUE_CY,
     MaliEngSlotAnyIssueCy},
    {"MaliGeomPosShadPartTask",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_POS_SHAD_PART_TASK,
     MaliGeomPosShadPartTask},
    {"MaliGeomVarShadPartTask",
     protos::pbzero::ArmGpuCounters::MALI_GEOM_VAR_SHAD_PART_TASK,
     MaliGeomVarShadPartTask},
    {"MaliFragPrepassKillRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_KILL_RATE,
     MaliFragPrepassKillRate},
    {"MaliFragMainPassStallRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_MAIN_PASS_STALL_RATE,
     MaliFragMainPassStallRate},
    {"MaliFragInputPrim", protos::pbzero::ArmGpuCounters::MALI_FRAG_INPUT_PRIM,
     MaliFragInputPrim},
    {"MaliFragPrepassPrimRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_PRIM_RATE,
     MaliFragPrepassPrimRate},
    {"MaliFragPrepassCullPrimRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_CULL_PRIM_RATE,
     MaliFragPrepassCullPrimRate},
    {"MaliFragPrepassUncullPrimRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_UNCULL_PRIM_RATE,
     MaliFragPrepassUncullPrimRate},
    {"MaliFragPrepassWarpRate",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_WARP_RATE,
     MaliFragPrepassWarpRate},
    {"MaliFragPrepassThread",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_PREPASS_THREAD,
     MaliFragPrepassThread},
    {"MaliFragMainThread",
     protos::pbzero::ArmGpuCounters::MALI_FRAG_MAIN_THREAD, MaliFragMainThread},
    {"MaliEngSlot0IssueCy",
     protos::pbzero::ArmGpuCounters::MALI_ENG_SLOT0_ISSUE_CY,
     MaliEngSlot0IssueCy},
    {"MaliEngAttrBackpressureRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_ATTR_BACKPRESSURE_RATE,
     MaliEngAttrBackpressureRate},
    {"MaliEngBlendBackpressureRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_BLEND_BACKPRESSURE_RATE,
     MaliEngBlendBackpressureRate},
    {"MaliEngLSBackpressureRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_LS_BACKPRESSURE_RATE,
     MaliEngLSBackpressureRate},
    {"MaliEngTexBackpressureRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_TEX_BACKPRESSURE_RATE,
     MaliEngTexBackpressureRate},
    {"MaliEngVarBackpressureRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_VAR_BACKPRESSURE_RATE,
     MaliEngVarBackpressureRate},
    {"MaliEngZSBackpressureRate",
     protos::pbzero::ArmGpuCounters::MALI_ENG_ZS_BACKPRESSURE_RATE,
     MaliEngZSBackpressureRate},

};

// Returns a lookup table of arm gpu counter names addressable by counter id.
inline std::vector<const char*> BuildArmGpuinfoCounterNames() {
  int max_id = 0;
  for (size_t i = 0; i < base::ArraySize(kArmGpuInfoPBKeys); i++)
    max_id = std::max(max_id, kArmGpuInfoPBKeys[i].id);
  std::vector<const char*> v;
  v.resize(static_cast<size_t>(max_id) + 1);
  for (size_t i = 0; i < base::ArraySize(kArmGpuInfoPBKeys); i++)
    v[static_cast<size_t>(kArmGpuInfoPBKeys[i].id)] = kArmGpuInfoPBKeys[i].str;
  return v;
}

}  // namespace profiling
}  // namespace perfetto

#endif  // SRC_PROFILING_MTK_DIMPROFD_ARM_GPU_COUNTER_ARM_GPU_COUNTERS_H_
