import("../../../../gn/test.gni")

source_set("arm_gpu_stats") {
  public_deps = [
    "../../../../gn:lib_gpu_counters",
    "../../../tracing/core",
  ]
  deps = [
    "..:data_source",
    "../../../../gn:default_deps",
    "../../../../gn:lib_gpu_counters",
    "../../../../include/perfetto/ext/traced",
    "../../../../protos/perfetto/common:zero",
    # "../../../../protos/perfetto/config:arm_gpu_counters:zero",
    "../../../../protos/perfetto/trace:zero",
    # "../../../../protos/perfetto/trace/profiling/arm_gpu_stats:zero",
    "../../../base",
    ":arm_gpu_counters",
  ]
  sources = [
    "arm_gpu_stats_data_source.cc",
    "arm_gpu_stats_data_source.h",
  ]
}

source_set("arm_gpu_counters") {
  sources = [
    "arm_gpu_counters.h",
  ]
  public_deps = [
    "../../../../gn:lib_gpu_counters_hwcpipe_counters",
    "../../../tracing/core",
  ]
  deps = [
    "../../../../gn:lib_gpu_counters_hwcpipe_counters",
  ]
}
# perfetto_unittest_source_set("unittests") {
#   testonly = true
#   deps = [
#     ":arm_gpu_stats",
#     "../../../../gn:default_deps",
#     "../../../../gn:gtest_and_gmock",
#     "../../../../protos/perfetto/trace/arm_gpu_stats:cpp",
#     "../../../../src/tracing/test:test_support",
#     "../common:test_support",
#   ]
#   sources = [ "arm_gpu_stats_data_source_unittest.cc" ]
# }
